# Generated by Django 2.0.6 on 2020-11-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201110_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='createneworder',
            name='address',
            field=models.CharField(default='arbat', max_length=150),
            preserve_default=False,
        ),
    ]
