# Generated by Django 2.0.6 on 2020-11-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_createneworder_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='createneworder',
            name='date_add_order',
            field=models.DateTimeField(auto_now_add=True, default='2020-11-06 13:15:05.426644'),
            preserve_default=False,
        ),
    ]
