# Generated by Django 2.0.6 on 2020-11-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_createneworder_date_add_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='createneworder',
            name='fio',
            field=models.CharField(default='ИГгнаткин Ильтя Алексеевич', max_length=150),
            preserve_default=False,
        ),
    ]
