# Generated by Django 2.0.6 on 2020-12-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_createneworder_fio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createneworder',
            options={'verbose_name': 'Заказы', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Аккаунты', 'verbose_name_plural': 'Аккаунты'},
        ),
        migrations.AlterField(
            model_name='createneworder',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Адресс аптеки'),
        ),
        migrations.AlterField(
            model_name='createneworder',
            name='all_product_id_and_count',
            field=models.CharField(max_length=1000, verbose_name='Список товаров'),
        ),
        migrations.AlterField(
            model_name='createneworder',
            name='contact',
            field=models.CharField(max_length=100, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='createneworder',
            name='date_add_order',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления'),
        ),
        migrations.AlterField(
            model_name='createneworder',
            name='fio',
            field=models.CharField(max_length=150, verbose_name='Ф.И.О'),
        ),
        migrations.AlterField(
            model_name='createneworder',
            name='method_of_obtaining',
            field=models.CharField(max_length=100, verbose_name='Метод доставки'),
        ),
        migrations.AlterField(
            model_name='createneworder',
            name='payment_method',
            field=models.CharField(max_length=100, verbose_name='Метод оплаты'),
        ),
        migrations.AlterField(
            model_name='createneworder',
            name='status',
            field=models.CharField(choices=[('qwe', 'В процессе тест'), ('qwe1', 'В процессе тест')], default='В процессе', max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='createneworder',
            name='sum_all',
            field=models.FloatField(verbose_name='Общая цена'),
        ),
        migrations.AlterField(
            model_name='createneworder',
            name='user',
            field=models.CharField(max_length=100, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='patronymic',
            field=models.CharField(max_length=30, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Телефон'),
        ),
    ]
