# Generated by Django 2.0.6 on 2020-12-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201201_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createneworder',
            name='fio',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ф.И.О'),
        ),
        migrations.AlterField(
            model_name='createneworder',
            name='status',
            field=models.CharField(blank=True, choices=[('status_1', 'В процессе'), ('status_2', 'Ожидает'), ('status_3', 'Выполнено'), ('line_width', '______________________________________________________________________')], default='В процессе', max_length=200, verbose_name='Статус'),
        ),
    ]
