# Generated by Django 2.0.6 on 2020-12-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201201_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createneworder',
            name='status',
            field=models.CharField(choices=[('status_1', 'В процессе'), ('status_2', 'Ожидает'), ('status_3', 'Выполнено'), ('line_width', '______________________________________________________________________')], max_length=200, verbose_name='Статус'),
        ),
    ]
