# Generated by Django 2.2.12 on 2020-12-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201201_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCodeSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Имя продукта')),
                ('image', models.ImageField(upload_to='', verbose_name='QR image')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'QR code',
                'verbose_name_plural': 'QR code',
            },
        ),
    ]
