# Generated by Django 2.2.12 on 2020-12-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_qrcodesave'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodesave',
            name='user',
            field=models.CharField(default=1, max_length=100, verbose_name='Логин'),
            preserve_default=False,
        ),
    ]
