# Generated by Django 2.2.12 on 2020-12-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_qrcodesave_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodesave',
            name='status',
            field=models.CharField(choices=[('status_1', 'Ожидает'), ('status_2', 'Одобренно'), ('status_3', 'Отказано')], default=1, max_length=200, verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qrcodesave',
            name='product_name',
            field=models.CharField(max_length=200, verbose_name='Имя продукта и количество'),
        ),
    ]
