# Generated by Django 2.2.12 on 2020-12-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20201210_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodesave',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во продукта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qrcodesave',
            name='product_name',
            field=models.CharField(max_length=200, verbose_name='Имя продукта '),
        ),
    ]
