# Generated by Django 2.2.12 on 2020-12-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20201210_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodesave',
            name='qr_value',
            field=models.CharField(default='12312312321fdsfe', max_length=1000, verbose_name='Значение QR'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qrcodesave',
            name='product_name',
            field=models.CharField(max_length=200, verbose_name='Имя продукта'),
        ),
    ]
