# Generated by Django 2.2.12 on 2020-12-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_qrcodesave_id_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodesave',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Коментарий'),
        ),
    ]
