# Generated by Django 2.1.12 on 2020-12-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_qrcodesave_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodesave',
            name='status',
            field=models.CharField(choices=[('status_1', 'Ожидает'), ('status_2', 'Одобренно'), ('status_3', 'Отказано'), ('status_4', 'Использовано')], max_length=200, verbose_name='Статус'),
        ),
    ]
