# Generated by Django 2.1.12 on 2020-12-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20201215_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='createneworder',
            name='all_product_id_and_count_dict',
            field=models.CharField(default='hello', max_length=1000, verbose_name='Список товаров список'),
            preserve_default=False,
        ),
    ]
