# Generated by Django 2.1.12 on 2020-12-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_createneworder_all_product_id_and_count_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createneworder',
            name='all_product_id_and_count_dict',
            field=models.CharField(max_length=1000, verbose_name='Список товаров dict'),
        ),
    ]
