# Generated by Django 2.1.12 on 2020-12-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20201222_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Доставка')),
                ('add_price', models.CharField(max_length=200, verbose_name='Плюс к стоимости')),
                ('min_sum_price_order', models.CharField(max_length=200, verbose_name='Мин стоимость заказа')),
            ],
            options={
                'verbose_name': 'Цены за доставку',
                'verbose_name_plural': 'Цены за доставку',
            },
        ),
    ]
