# Generated by Django 2.1.12 on 2020-12-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_pricedelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedelivery',
            name='add_price',
            field=models.PositiveIntegerField(verbose_name='Кол-во продукта'),
        ),
        migrations.AlterField(
            model_name='pricedelivery',
            name='min_sum_price_order',
            field=models.PositiveIntegerField(verbose_name='Кол-во продукта'),
        ),
    ]
