# Generated by Django 2.1.12 on 2021-01-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20201222_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AlterField(
            model_name='pricedelivery',
            name='add_price',
            field=models.PositiveIntegerField(verbose_name='Плюс к стоимости'),
        ),
        migrations.AlterField(
            model_name='pricedelivery',
            name='min_sum_price_order',
            field=models.PositiveIntegerField(verbose_name='Минимальная сумма заказа'),
        ),
    ]
