# Generated by Django 2.0.6 on 2020-11-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketproduct',
            name='quantity_of_goods',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
