# Generated by Django 2.0.6 on 2020-11-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0002_basketproduct_quantity_of_goods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketproduct',
            name='quantity_of_goods',
        ),
        migrations.AddField(
            model_name='basketproduct',
            name='count',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
    ]
