# Generated by Django 2.0.6 on 2020-11-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0004_createneworder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateNewOrder',
        ),
    ]
