# Generated by Django 2.0.6 on 2020-11-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0006_pharmacieaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacieaddress',
            old_name='title',
            new_name='address',
        ),
    ]
