# Generated by Django 2.0.6 on 2020-11-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0008_auto_20201112_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
    ]
