# Generated by Django 2.0.6 on 2020-11-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0009_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recipe',
            field=models.BooleanField(default=False),
        ),
    ]
