# Generated by Django 2.0.6 on 2020-11-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0011_basketproduct_login_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='methods_of_application',
            field=models.TextField(default='Способ применения'),
            preserve_default=False,
        ),
    ]
