# Generated by Django 2.0.6 on 2020-11-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0012_product_methods_of_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200)),
                ('id_product', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('heading_reviev', models.CharField(max_length=200)),
                ('text_reviev', models.CharField(max_length=200)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
