# Generated by Django 2.0.6 on 2020-11-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0015_auto_20201127_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.TextField(default='Информация отсутствует.'),
        ),
    ]
