# Generated by Django 2.0.6 on 2020-11-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0016_auto_20201127_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thermobox',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.TextField(default='Информация отсутствует. '),
        ),
    ]
