# Generated by Django 2.0.6 on 2020-11-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0017_auto_20201127_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.CharField(default='company', max_length=100),
            preserve_default=False,
        ),
    ]
