# Generated by Django 2.0.6 on 2020-12-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0019_auto_20201201_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
