# Generated by Django 2.0.6 on 2020-12-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0020_auto_20201201_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumb',
            field=models.ImageField(upload_to=''),
        ),
    ]
