# Generated by Django 2.0.6 on 2020-12-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0022_auto_20201201_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketproduct',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='pharmacieaddress',
            options={'verbose_name': 'Адреса аптек', 'verbose_name_plural': 'Адреса аптек'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товары', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='qrcodesave',
            options={'verbose_name': 'QR code', 'verbose_name_plural': 'QR code'},
        ),
        migrations.AlterModelOptions(
            name='reviev',
            options={'verbose_name': 'Отзывы', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='basketproduct',
            name='count',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='basketproduct',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='basketproduct',
            name='login',
            field=models.CharField(max_length=100, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='basketproduct',
            name='login_hash',
            field=models.CharField(max_length=100, verbose_name='Клиент hash'),
        ),
        migrations.AlterField(
            model_name='basketproduct',
            name='product_done',
            field=models.BooleanField(default=False, verbose_name='Есть в наличии'),
        ),
        migrations.AlterField(
            model_name='basketproduct',
            name='product_id',
            field=models.CharField(max_length=100, verbose_name='ID Продукта'),
        ),
        migrations.AlterField(
            model_name='basketproduct',
            name='setting_product',
            field=models.TextField(verbose_name='Настройки'),
        ),
        migrations.AlterField(
            model_name='pharmacieaddress',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='pharmacieaddress',
            name='city',
            field=models.CharField(max_length=200, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='product',
            name='application_methods',
            field=models.TextField(default='Информация отсутствует.', verbose_name='Способ применения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.TextField(default='Информация отсутствует. ', verbose_name='Харатеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.CharField(max_length=100, verbose_name='Компания/Поставщик'),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.TextField(default='Информация отсутствует.', verbose_name='Состав/Действующие вещества'),
        ),
        migrations.AlterField(
            model_name='product',
            name='contraindications',
            field=models.TextField(default='Информация отсутствует.', verbose_name='Противопоказания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(verbose_name='Кол-во в упаковки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Информация отсутствует.', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='general_description',
            field=models.TextField(default='Информация отсутствует.', verbose_name='Общие описания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='indications',
            field=models.TextField(default='Информация отсутствует.', verbose_name='Показания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Кол-во в наличии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recipe',
            field=models.BooleanField(default=False, verbose_name='С рецептом ДА/НЕТ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thermobox',
            field=models.BooleanField(default=False, verbose_name='Термозависимость ДА/НЕТ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumb',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='qrcodesave',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='qrcodesave',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='QR image'),
        ),
        migrations.AlterField(
            model_name='qrcodesave',
            name='title',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='reviev',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='reviev',
            name='heading_reviev',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='reviev',
            name='id_product',
            field=models.CharField(max_length=100, verbose_name='ID Продукта'),
        ),
        migrations.AlterField(
            model_name='reviev',
            name='login',
            field=models.CharField(max_length=200, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='reviev',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано ДА/НЕТ'),
        ),
        migrations.AlterField(
            model_name='reviev',
            name='text_reviev',
            field=models.CharField(max_length=200, verbose_name='Отзыв'),
        ),
    ]
