# Generated by Django 2.0.6 on 2020-12-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0023_auto_20201201_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active_substances',
            field=models.TextField(default='Информация отсутствует.', verbose_name='Активные вещества'),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.TextField(default='Информация отсутствует.', verbose_name='Состав'),
        ),
    ]
