# Generated by Django 2.2.12 on 2020-12-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0024_auto_20201201_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.IntegerField(default=0, verbose_name='Пордажи'),
        ),
        migrations.AddField(
            model_name='product',
            name='watches',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
