# Generated by Django 2.2.12 on 2020-12-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0025_auto_20201205_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sales',
            field=models.IntegerField(default=0, verbose_name='Продажи'),
        ),
    ]
