# Generated by Django 2.2.12 on 2020-12-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0026_auto_20201206_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Цена со скидкой'),
            preserve_default=False,
        ),
    ]
