# Generated by Django 2.2.12 on 2020-12-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0031_productdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdescription',
            name='position',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='video_url',
        ),
        migrations.AddField(
            model_name='productdescription',
            name='text',
            field=models.TextField(default=12, verbose_name='Текст в описании'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Название описания'),
        ),
    ]
