# Generated by Django 2.2.12 on 2020-12-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0032_auto_20201210_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='characteristics',
        ),
        migrations.RemoveField(
            model_name='product',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='contraindications',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='general_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='indications',
        ),
    ]
