# Generated by Django 2.2.12 on 2020-12-10 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0035_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QrCodeSave',
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
    ]
