# Generated by Django 2.1.12 on 2020-12-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0037_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='testimony',
            field=models.TextField(default='Информация отсутствует.', max_length=100, verbose_name='Показания'),
        ),
    ]
