# Generated by Django 2.1.12 on 2020-12-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0038_product_testimony'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdescription',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.BooleanField(default=False, verbose_name='Коментарии ДА/НЕТ'),
        ),
    ]
