# Generated by Django 2.1.12 on 2020-12-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0039_auto_20201214_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrollBarHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('img', models.ImageField(blank=True, upload_to='', verbose_name='Изображение')),
                ('href_button', models.CharField(blank=True, max_length=1000, verbose_name='Ссылка кнопки')),
                ('background_color', models.CharField(max_length=200, verbose_name='Цвет заднего фона')),
                ('text_color', models.CharField(max_length=200, verbose_name='Цвет текста')),
                ('image_background', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение занего фона НЕ обязательно')),
            ],
            options={
                'verbose_name': 'Скролбар домашняя страница',
                'verbose_name_plural': 'Скролбар домашняя страница',
            },
        ),
        migrations.AlterModelOptions(
            name='productdescription',
            options={'verbose_name': 'Описание всех товаров', 'verbose_name_plural': 'Описание всех товаров'},
        ),
        migrations.AlterField(
            model_name='product',
            name='testimony',
            field=models.TextField(default='Информация отсутствует.', verbose_name='Показания'),
        ),
    ]
