# Generated by Django 2.1.12 on 2020-12-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0040_auto_20201222_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrollbarhome',
            name='title_color',
            field=models.CharField(default='black', max_length=200, verbose_name='Цвет заголовка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scrollbarhome',
            name='text_color',
            field=models.CharField(max_length=200, verbose_name='Цвет текста '),
        ),
    ]
