# Generated by Django 2.1.12 on 2020-12-22 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0042_scrollbardiscount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrollbardiscount',
            options={'verbose_name': 'НЕ ДОБАВЛЯТЬ!!!', 'verbose_name_plural': 'Скролбар cтраница со скидками НЕ УДАЛЯТЬ ИЛИ ДОБАВЛЯТЬ ЗАПИСИ ТОЛЬКО РЕДАКТИРОВАТЬ  '},
        ),
        migrations.AlterModelOptions(
            name='scrollbarhome',
            options={'verbose_name': 'НЕ ДОБАВЛЯТЬ!!!', 'verbose_name_plural': 'Скролбар домашняя страница НЕ УДАЛЯТЬ ИЛИ ДОБАВЛЯТЬ ЗАПИСИ ТОЛЬКО РЕДАКТИРОВАТЬ'},
        ),
    ]
