# Generated by Django 2.1.12 on 2021-01-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0043_auto_20201222_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrollbardiscount',
            options={'verbose_name': '', 'verbose_name_plural': 'Скролбар cтраница со скидками'},
        ),
        migrations.AlterModelOptions(
            name='scrollbarhome',
            options={'verbose_name': '', 'verbose_name_plural': 'Скролбар домашняя страница'},
        ),
    ]
