# Generated by Django 3.1.5 on 2021-01-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0044_auto_20210113_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('img', models.ImageField(blank=True, upload_to='', verbose_name='Изображение')),
                ('watches', models.IntegerField(default=0, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
