# Generated by Django 3.1.5 on 2021-01-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_apteka', '0045_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='title_color',
            field=models.CharField(default='black', max_length=200, verbose_name='Цвет заголовка'),
            preserve_default=False,
        ),
    ]
